package main;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;




// this class changes csv training set generated by the software to a csv in a printable version.
// although this dose not make sense because printing covers more numbers than training set :)

public class CsvToPrintableCsv {

	
	
	
	public static void main(String[] args) {

	
	List<List<String>> records = new ArrayList<>();
	try (BufferedReader br = new BufferedReader(new FileReader("Trainingset_hash_50000_9_32mixOfHashes.csv"))) {
	    String line;
	    while ((line = br.readLine()) != null) {
	        String[] values = line.split(",");
	        records.add(Arrays.asList(values));
	    }
	} catch (IOException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	
	
	try (PrintWriter writer = new PrintWriter(new File("NewCSVFile.csv"))) {
		
	StringBuilder sb = new StringBuilder();
	
	//without titles?
	for (int x = 1; x < records.size(); x++) {
		
		
		//without YES/no collumn?
		for (int y = 0; y<records.get(x).size()-1;  y++) {
			
			
		
			sb.append(records.get(x).get(y));
			sb.append("-");
			
			
		}
		sb.append(',');
		
		
		//lenght of normal number
		for (int y = 0; y < 9;  y++) {
			
			
			
			sb.append(records.get(x).get(y));
			
			
			
		}
		sb.append('\n');
		
		
		
		
		
		
		
		
	}
		
	writer.write(sb.toString());
	} catch (FileNotFoundException e) {
		System.out.println(e.getMessage());
	}
	
	
	
	
	
//	
//	
//	try (PrintWriter writer = new PrintWriter(new File("NewCSVFile.csv"))) {
//
//		  //adding title to you table
//					StringBuilder sb = new StringBuilder();
//					sb.append("Column1");
//					sb.append(',');
//					sb.append("Column2");
//					sb.append('\n');
//
//		  //adding data in rows
//					for (int x = 0; x < 10000; x++) {
//
//
//			
//						sb.append(aes.encrypt("AA" + x, password));
//						sb.append(',');
//						sb.append("Correct");
//						sb.append('\n');
//						
//
//					}
//
//		//writing to file
//					writer.write(sb.toString());
//
//					System.out.println("done!");
//
//				} catch (FileNotFoundException e) {
//					System.out.println(e.getMessage());
//				}
//	
	
	}
	
	
	
	
	
	
	
	
	
	
}
